from .ColorStrategy import ColorStrategy
from .BlueColor import BlueColor
from .BrownColor import BrownColor
from .ElectricBlueColor import ElectricBlueColor
from .GreenColor import GreenColor
from .LightBlueColor import LightBlueColor
from .OrangeColor import OrangeColor
from .PurpleColor import PurpleColor
from .RedColor import RedColor
from .SteelGrayColor import SteelGrayColor